### ISSUE TITLE
Builds failing with v1.3.1

### ISSUE THREAD

**Issue by impressiver** [unsplash/comment-on-pr#51]
Upgrading to `unsplash/comment-on-pr@v1.3.1` causes our builds to fail w/ the following error:

```
/entrypoint.sh:5:in `require_relative': cannot load such file -- /lib/github (LoadError)
	from /entrypoint.sh:5:in `<main>'
```

Downgrading to `unsplash/comment-on-pr@v1.3.0` fixed our builds for now.

**Comment by aaronklaassen** [comment]
I don't have time to address this right now but reverted the breaking PR on master in the meantime.

**Comment by nubcake94** [comment]
@aaronklaassen 1.3.0 breaks as well now with the following error
![image](https://user-images.githubusercontent.com/47889408/148420403-fa55e2a6-5e77-4e01-aa8d-78197f37e8e9.png)

**Comment by drewbrew** [comment]
FWIW, 1.2.0 builds but does not run:
```
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- /usr/local/bundle/gems/faraday-1.9.0/lib/faraday/request/retry (LoadError)
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/default.rb:28:in `block in <module:Default>'
	from /usr/local/bundle/gems/faraday-1.9.0/lib/faraday/rack_builder.rb:76:in `build'
	from /usr/local/bundle/gems/faraday-1.9.0/lib/faraday/rack_builder.rb:65:in `initialize'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/default.rb:27:in `new'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/default.rb:27:in `<module:Default>'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/default.rb:9:in `<module:Octokit>'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/default.rb:6:in `<top (required)>'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /entrypoint.sh:4:in `<main>'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- octokit (LoadError)
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /entrypoint.sh:4:in `<main>'
```

**Comment by kirach** [comment]
looks like 1.3.0 stopped working too due to the same error @drewbrew posted above

**Comment by impressiver** [comment]
> looks like 1.3.0 stopped working too due to the same error @drewbrew posted above

Broke for us too for a short time this morning, but builds are building again pinned to v1.3.0

**Comment by jbuettnerbild** [comment]
v1.3.0 stopped working since yesterday and v1.3.1 dosnt work also. 
Please fix this.

**Comment by drewbrew** [comment]
> builds are building again pinned to v1.3.0

Same here, luckily

**Comment by dgrenner** [comment]
@aaronklaassen, would it be possible to create a new tag (v1.3.2) from master? With automatic dependency updates (using Renovate bot / dependabot) it's easy to end up on v1.3.1.

**Comment by wblondel** [comment]
A new tag would indeed be really useful.

**Comment by ruudk** [comment]
For anyone trying to work around this broken action, I decided to use the `gh` cli instead:
```yaml
-   name: Add comment on PR
    run: |
        cat << EOF | gh pr comment ${{ github.event.pull_request.number }} --body-file -
        Hello from
        GitHub Actions
        EOF
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Unfortunately, there is no duplication check in the `gh` cli.

**Comment by sjortiz** [comment]
any updates?

**Comment by Lockyy** [comment]
This also broke our deploys when we upgraded from 1.3.0 to 1.3.1 with the error from the OP:

```
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
/entrypoint.sh:5:in `require_relative': cannot load such file -- /lib/github (LoadError)
	from /entrypoint.sh:5:in `<main>'
```

Reverting to 1.3.0 fixed the issue.

I noticed looking through the commits for the change from 1.3.0 to 1.3.1 that there's been a major refactor, would that be worthy of a major/minor version bump rather than a patch version change.

**Comment by apotek** [comment]
> This also broke our deploys when we upgraded from 1.3.0 to 1.3.1 with the error from the OP:
> 
> ```
> To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
> /entrypoint.sh:5:in `require_relative': cannot load such file -- /lib/github (LoadError)
> 	from /entrypoint.sh:5:in `<main>'
> ```
> 
> Reverting to 1.3.0 fixed the issue.
> 
> I noticed looking through the commits for the change from 1.3.0 to 1.3.1 that there's been a major refactor, would that be worthy of a major/minor version bump rather than a patch version change.

This exact issue is happening for us too, but it was already happening in 1.3.0  and I was hoping 1.3.1 would fix it :(. 

```
" "true" "" ""
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
/entrypoint.sh:5:in `require_relative': cannot load such file -- /lib/github (LoadError)
	from /entrypoint.sh:5:in `<main>'
```

Looks like the CLI route is the way to go.
